image: Visual Studio 2019
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

nuget:
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: |
      Invoke-WebRequest https://github.com/benjamin-hodgson/BuildScripts/archive/master.zip -OutFile BuildScripts.zip
      Expand-Archive BuildScripts.zip -Destination .
      mv BuildScripts-master BuildScripts

  - ps: .\BuildScripts\appveyor\InitBuildNumber.ps1
  - cmd: msbuild FixedSizeBuffers.sln /t:restore /p:Configuration=%CONFIGURATION% /v:Minimal
  - cmd: cinst docfx
  - ps: .\BuildScripts\appveyor\ConfigureGit.ps1

build:
  project: FixedSizeBuffers.sln
  verbosity: minimal

after_test:
  - cmd: msbuild FixedSizeBuffers.sln /t:pack /p:Configuration=%CONFIGURATION% /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg /p:PackageOutputPath=..\nupkgs /v:Minimal

artifacts:
  - type: NuGetPackage
    path: nupkgs/*.nupkg

deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: fTNnLrnJ3Jlz+WdkRFIEr0lJOsqjy7thdKgLvgpCMWDG3SFvlrJJGSZp5PVbDtfy
  on:
    appveyor_repo_tag: true
